// <auto-generated />
using System;
using FIAP.Global_ImpactWeb.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FIAP.Global_ImpactWeb.Migrations
{
    [DbContext(typeof(SolutionContext))]
    [Migration("20211116231735_BugDelete")]
    partial class BugDelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.ContaBancaria", b =>
                {
                    b.Property<int>("ContaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agencia")
                        .HasColumnType("int");

                    b.Property<string>("NomeBanco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("int");

                    b.HasKey("ContaId");

                    b.ToTable("T_CONTA_BANCARIAS");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.Doacao", b =>
                {
                    b.Property<int>("DoacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("CodigoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtDoacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailDoador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDoador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantia")
                        .HasColumnType("real");

                    b.HasKey("DoacaoId");

                    b.HasIndex("CodigoId");

                    b.ToTable("T_DOACAO");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEP")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Sigla")
                        .HasColumnType("int");

                    b.HasKey("EnderecoId");

                    b.ToTable("T_ENDERECO");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.UserONG", b =>
                {
                    b.Property<int>("CodigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<string>("LinkSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoId");

                    b.HasIndex("ContaId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("T_ONG");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.Doacao", b =>
                {
                    b.HasOne("FIAP.Global_ImpactWeb.Models.UserONG", "UserONG")
                        .WithMany("Doacoes")
                        .HasForeignKey("CodigoId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("UserONG");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.UserONG", b =>
                {
                    b.HasOne("FIAP.Global_ImpactWeb.Models.ContaBancaria", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIAP.Global_ImpactWeb.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("FIAP.Global_ImpactWeb.Models.UserONG", b =>
                {
                    b.Navigation("Doacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
